export const Cookies = {
  PreferredSignInProvider: "preferred-signin-provider",
  SpendingPeriod: "spending-period",
  ChartType: "chart-type",
  TransactionsPeriod: "transactions-period",
  TransactionsColumns: "transactions-columns",
  MfaSetupVisited: "mfa-setup-visited",
  MenuConfig: "menu-config",
  InboxFilter: "inbox-filter-v2",
  MobileOverlay: "mobile-overlay",
  TrackingConsent: "tracking-consent",
  ChartCurrency: "chart-currency",
  InboxOrder: "inbox-order",
  CountryCode: "country-code",
};
