import { Text, View } from "@react-pdf/renderer";

type AuditFooterProps = {
  templateVersion: string;
  generatedAt: string;
  documentHash?: string;
  calculationVersion: string;
};

export function AuditFooter({
  templateVersion,
  generatedAt,
  documentHash,
  calculationVersion,
}: AuditFooterProps) {
  return (
    <View
      style={{
        borderTop: "1px solid #e2e8f0",
        paddingTop: 8,
        marginTop: "auto",
      }}
      fixed
    >
      <Text
        style={{
          fontSize: 6,
          color: "#94a3b8",
          textAlign: "center",
          marginBottom: 2,
        }}
      >
        Disclosure Version: {templateVersion} | Calculation Engine:{" "}
        {calculationVersion} | Generated: {generatedAt}
      </Text>
      {documentHash && (
        <Text
          style={{
            fontSize: 6,
            color: "#94a3b8",
            textAlign: "center",
            marginBottom: 2,
          }}
        >
          Document Hash (SHA-256): {documentHash}
        </Text>
      )}
      <Text
        style={{
          fontSize: 6,
          color: "#94a3b8",
          textAlign: "center",
        }}
      >
        Generated by Abacus | This document is for informational purposes and
        constitutes the required disclosure under applicable state law.
      </Text>
    </View>
  );
}
