import { z } from "zod";

// TransactionInternal Schema
export const TransactionInternalSchema = z.object({
  AccountId: z.string(),
  AccountOwner: z.string(),
  Amount: z.number(),
  AuthorizedDate: z.string(),
  AuthorizedDatetime: z.string(),
  CategoryId: z.string(),
  CheckNumber: z.string().nullable(),
  CurrentDate: z.string(),
  CurrentDatetime: z.string(),
  ID: z.string().uuid(),
  IsoCurrencyCode: z.string(),
  LinkId: z.number().int(),
  LocationAddress: z.string().nullable(),
  LocationCity: z.string().nullable(),
  LocationCountry: z.string().nullable(),
  LocationLat: z.number().nullable(),
  LocationLon: z.number().nullable(),
  LocationPostalCode: z.string().nullable(),
  LocationRegion: z.string().nullable(),
  LocationStoreNumber: z.string().nullable(),
  MerchantName: z.string(),
  Name: z.string(),
  PaymentChannel: z.string(),
  PaymentMetaByOrderOf: z.string().nullable(),
  PaymentMetaPayee: z.string().nullable(),
  PaymentMetaPayer: z.string().nullable(),
  PaymentMetaPaymentMethod: z.string().nullable(),
  PaymentMetaPaymentProcessor: z.string().nullable(),
  PaymentMetaPpdId: z.string().nullable(),
  PaymentMetaReason: z.string().nullable(),
  PaymentMetaReferenceNumber: z.string().nullable(),
  Pending: z.boolean(),
  PendingTransactionId: z.string().nullable(),
  PersonalFinanceCategoryDetailed: z.string(),
  PersonalFinanceCategoryPrimary: z.string(),
  Sign: z.number().int().min(-1).max(1),
  Time: z.date(),
  TransactionCode: z.string().nullable(),
  TransactionId: z.string(),
  UnofficialCurrencyCode: z.string().nullable(),
  UserId: z.string().uuid(),
  Categories: z.array(z.string()),
  ProfileType: z.string(),
});

// ReOccuringTransactionInternal Schema
export const ReOccuringTransactionInternalSchema = z.object({
  AccountId: z.string(),
  AverageAmount: z.string(),
  AverageAmountIsoCurrencyCode: z.string(),
  CategoryId: z.string(),
  Description: z.string(),
  FirstDate: z.string(),
  Flow: z.string(),
  Frequency: z.string(),
  ID: z.string().uuid(),
  IsActive: z.boolean(),
  LastAmount: z.string(),
  LastAmountIsoCurrencyCode: z.string(),
  LastDate: z.string(),
  LinkId: z.number().int(),
  MerchantName: z.string(),
  PersonalFinanceCategoryDetailed: z.string(),
  PersonalFinanceCategoryPrimary: z.string(),
  Sign: z.number().int().min(-1).max(1),
  Status: z.string(),
  StreamId: z.string(),
  Time: z.date(),
  TransactionIds: z.string(),
  UpdatedTime: z.string(),
  UserId: z.string().uuid(),
  ProfileType: z.string(),
});

// AccountBalanceHistoryInternal Schema
export const AccountBalanceHistoryInternalSchema = z.object({
  Time: z.date(),
  AccountId: z.string(),
  IsoCurrencyCode: z.string(),
  Balance: z.number(),
  UserId: z.string().uuid(),
  Sign: z.number().int().min(-1).max(1),
  Id: z.string().uuid(),
  ProfileType: z.string(),
});
