name: Setup
description: Setup Bun, cache dependencies, and install

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: v1.3.9

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          **/node_modules
          .turbo
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      shell: bash
      run: bun install
