// Export all logos from a single file
export { Logo as GmailLogo } from "./gmail/assets/logo";
export { Logo as OutlookLogo } from "./outlook/assets/logo";
export { Logo as SlackLogo } from "./slack/assets/logo";
export { Logo as WhatsAppLogo } from "./whatsapp/assets/logo";
export { Logo as XeroLogo } from "./xero/assets/logo";
export { Logo as QuickBooksLogo } from "./quick-books/assets/logo";
export { Logo as FortnoxLogo } from "./fortnox/assets/logo";
export { Logo as RaycastLogo } from "./raycast/assets/logo";
export { Logo as StripeLogo } from "./stripe/assets/logo";
export { Logo as StripePaymentsLogo } from "./stripe-payments/assets/logo";
export { Logo as MiddayDesktopLogo } from "./midday-desktop/assets/logo";
export { Logo as GoogleDriveLogo } from "./google-drive/assets/logo";
export { Logo as DropboxLogo } from "./dropbox/assets/logo";
export { Logo as PolarLogo } from "./polar/assets/logo";
export { Logo as DeelLogo } from "./deel/assets/logo";
export { Logo as EInvoiceLogo } from "./e-invoice/assets/logo";
