import { IntegrationCategory, ModellingIntegrationConfig } from "../../types";
import { Logo } from "./assets/logo";
import { initialize } from "./initialize";

const productProfitabilityModelling: ModellingIntegrationConfig = {
  name: "Product/Service Profitability Model",
  id: "product-profitability-model",
  category: IntegrationCategory.Modelling,
  active: true,
  logo: Logo,
  short_description:
    "Analyze profitability of individual products or services.",
  description:
    "Product/Service Profitability Model helps businesses assess whether individual products or services are profitable by isolating their revenue and associated costs. It provides insights into the financial performance of specific offerings.",
  images: [],
  onInitialize: initialize,
  settings: [
    {
      id: "total_revenue",
      label: "Total Revenue from Product",
      description: "Enter the total revenue generated by the product/service",
      type: "number",
      required: true,
      value: 0,
      min: 0,
    },
    {
      id: "product_cost",
      label: "Product Cost",
      description: "Enter the direct cost of producing the product/service",
      type: "number",
      required: true,
      value: 0,
      min: 0,
    },
    {
      id: "marketing_overhead",
      label: "Marketing + Overhead",
      description:
        "Enter the marketing and overhead costs associated with the product/service",
      type: "number",
      required: true,
      value: 0,
      min: 0,
    },
    {
      id: "time_period",
      label: "Time Period",
      description: "Select the time period for the analysis",
      type: "select",
      required: true,
      value: "monthly",
      options: ["monthly", "quarterly", "annually"],
    },
  ],
  config: {
    resultFields: [
      { id: "product_profitability", label: "Product Profitability" },
      { id: "total_revenue", label: "Total Revenue" },
      { id: "total_costs", label: "Total Costs" },
    ],
  },
  equation: {
    formula:
      "Product Profitability = Total Revenue from Product - (Product Cost + Marketing + Overhead)",
    variables: {
      "Total Revenue from Product": {
        label: "Total Revenue from Product",
        description: "Total revenue generated by the product/service",
        unit: "currency",
      },
      "Product Cost": {
        label: "Product Cost",
        description: "Direct cost of producing the product/service",
        unit: "currency",
      },
      "Marketing + Overhead": {
        label: "Marketing + Overhead",
        description:
          "Marketing and overhead costs associated with the product/service",
        unit: "currency",
      },
    },
    calculate: (variables) => {
      const totalRevenue = variables["Total Revenue from Product"] ?? 0;
      const productCost = variables["Product Cost"] ?? 0;
      const marketingOverhead = variables["Marketing + Overhead"] ?? 0;

      const totalCosts = productCost + marketingOverhead;
      const productProfitability = totalRevenue - totalCosts;

      return {
        product_profitability: productProfitability,
        total_revenue: totalRevenue,
        total_costs: totalCosts,
      };
    },
  },
};

export default productProfitabilityModelling;
