/**
 * Mock institution data for local development when Typesense is unavailable.
 * Uses real Plaid sandbox institution IDs so Connect flows work end-to-end.
 */

export type MockInstitution = {
  id: string;
  name: string;
  logo: string | null;
  provider: "plaid" | "gocardless" | "teller" | "enablebanking";
  popularity: number;
  countries: string[];
  available_history: number | null;
  maximum_consent_validity: number | null;
  type: "personal" | "business" | null;
};

export const mockInstitutions: MockInstitution[] = [
  {
    id: "ins_3",
    name: "Chase",
    logo: null,
    provider: "plaid",
    popularity: 100,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_1",
    name: "Bank of America",
    logo: null,
    provider: "plaid",
    popularity: 95,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_4",
    name: "Wells Fargo",
    logo: null,
    provider: "plaid",
    popularity: 90,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_5",
    name: "Citibank",
    logo: null,
    provider: "plaid",
    popularity: 85,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_12",
    name: "US Bank",
    logo: null,
    provider: "plaid",
    popularity: 80,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_13",
    name: "Capital One",
    logo: null,
    provider: "plaid",
    popularity: 75,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_14",
    name: "TD Bank",
    logo: null,
    provider: "plaid",
    popularity: 70,
    countries: ["US", "CA"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_15",
    name: "PNC Bank",
    logo: null,
    provider: "plaid",
    popularity: 65,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_16",
    name: "Truist",
    logo: null,
    provider: "plaid",
    popularity: 60,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_17",
    name: "Ally Bank",
    logo: null,
    provider: "plaid",
    popularity: 55,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_18",
    name: "Charles Schwab",
    logo: null,
    provider: "plaid",
    popularity: 50,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_19",
    name: "USAA",
    logo: null,
    provider: "plaid",
    popularity: 45,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_20",
    name: "Navy Federal Credit Union",
    logo: null,
    provider: "plaid",
    popularity: 40,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_21",
    name: "Citizens Bank",
    logo: null,
    provider: "plaid",
    popularity: 35,
    countries: ["US"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
  {
    id: "ins_127991",
    name: "Royal Bank of Canada",
    logo: null,
    provider: "plaid",
    popularity: 90,
    countries: ["CA"],
    available_history: 730,
    maximum_consent_validity: null,
    type: null,
  },
];
