export const chatExamples = [
  `What's my burn rate`,
  `What's my runway`,
  "Show transactions without receipts",
  "What is my spending on Software",
  "Find a receipt or invoice",
  "Find a transaction",
  `What's my profit for last year`,
  `What's my revenue`,
  "Create a report",
  "Forecast profit",
  "Forecast revenue",
  "Find a document",
  "Recurring transactions",
  "Top expenses this month",
];
