export const Jobs = {
  TRANSACTIONS_EXPORT: "transactions-export",
  TRANSACTIONS_NOTIFICATION: "transactions-notification",
  TRANSACTION_SCHEDULER: "transaction-scheduler",
  TRANSACTIONS_SYNC: "transactions-sync",
  TRANSACTIONS_SETUP: "transactions-setup",
  INBOX_DOCUMENT: "inbox-document",
  INBOX_MATCH: "inbox-match",
  INBOX_UPLOAD: "inbox-upload",
  TRANSACTIONS_INITIAL_SYNC: "transactions-initial-sync",
  TRANSACTIONS_MANUAL_SYNC: "transactions-manual-sync",
  TRANSACTIONS_IMPORT: "transactions-import",
  UPDATE_CURRENCY: "update-base-currency",
  BANK_CONNECTION_DISCONNECTED: "bank-connection-disconnected",
  BANK_CONNECTION_EXPIRING: "bank-connection-expiring",
  EXCHANGE_RATES_UPDATE: "exchange-rates-update",
  TRANSACTIONS_EXPORT_PDF: "transactions-export-pdf",
  IDENTIFY_UNUSUAL_TRANSACTIONS: "identify-unusual-transactions",
  GENERATE_TRANSACTION_SUMMARY: "generate-transaction-summary",
  REMOVE_OLD_TRANSACTIONS: "remove-old-transactions",
  GENERATE_TAX_SUMMARY: "generate-tax-summary",
  MANUALLY_SCHEDULE_TRANSACTION_SYNC: "manually-schedule-transaction-sync",
  TRANSACTION_SYNC_ALL_TEAMS: "transaction-sync-all-teams",
};

export const Events = {
  TRANSACTIONS_EXPORT: "transactions.export",
  TRANSACTIONS_NOTIFICATION: "transactions.notification",
  TRANSACTIONS_SETUP: "transactions.setup",
  INBOX_DOCUMENT: "inbox.document",
  INBOX_MATCH: "inbox.match",
  TRANSACTIONS_INITIAL_SYNC: "transactions.initial.sync",
  TRANSACTIONS_MANUAL_SYNC: "transactions.manual.sync",
  TRANSACTIONS_IMPORT: "transactions.import",
  UPDATE_CURRENCY: "update.base.currency",
  TRANSACTIONS_EXPORT_PDF: "transactions.export.pdf",
  IDENTIFY_UNUSUAL_TRANSACTIONS: "transactions.identify.unusual",
  GENERATE_TRANSACTION_SUMMARY: "transactions.generate.summary",
  REMOVE_OLD_TRANSACTIONS: "transactions.remove.old",
  GENERATE_TAX_SUMMARY: "transactions.generate.tax.summary",
  MANUALLY_SCHEDULE_TRANSACTION_SYNC: "manually.schedule.transaction.sync",
  TRANSACTION_SYNC_ALL_TEAMS: "transaction.sync.all.teams",
};
