import type { Metadata } from "next";
import { baseUrl } from "@/app/sitemap";

const title = "Privacy Policy";
const description =
  "Privacy Policy for Midday. Learn how we collect, use, and protect your personal data.";

export const metadata: Metadata = {
  title,
  description,
  openGraph: {
    title,
    description,
    type: "website",
    url: `${baseUrl}/policy`,
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
  alternates: {
    canonical: `${baseUrl}/policy`,
  },
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen">
      <div className="pt-12 sm:pt-16 lg:pt-20 pb-16 sm:pb-24">
        <div className="pt-12 sm:pt-16 lg:pt-24">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="space-y-8">
              <div className="space-y-4">
                <h1 className="font-serif text-2xl sm:text-3xl lg:text-3xl xl:text-3xl 2xl:text-3xl 3xl:text-4xl leading-tight lg:leading-tight xl:leading-[1.3] text-foreground">
                  Privacy Policy
                </h1>
                <p className="font-sans text-sm text-muted-foreground">
                  Last updated: October 26, 2023
                </p>
              </div>

              <div className="prose prose-sm sm:prose-base max-w-none space-y-6 font-sans text-foreground">
                <p className="text-muted-foreground leading-relaxed">
                  Midday Labs AB ("us", "we", or "our") operates the Midday
                  application (hereinafter referred to as the "Service").
                </p>

                <p className="text-muted-foreground leading-relaxed">
                  This page informs you of our policies regarding the
                  collection, use and disclosure of personal data when you use
                  our Service and the choices you have associated with that
                  data.
                </p>

                <p className="text-muted-foreground leading-relaxed">
                  We use your data to provide and improve the Service. By using
                  the Service, you agree to the collection and use of
                  information in accordance with this policy. Unless otherwise
                  defined in this Privacy Policy, the terms used in this Privacy
                  Policy have the same meanings as in our Terms and Conditions.
                </p>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Definitions
                  </h2>

                  <div className="space-y-4">
                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Service
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        Service is the Midday application operated by Midday
                        Labs AB
                      </p>
                    </div>

                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Personal Data
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        Personal Data means data about a living individual who
                        can be identified from those data (or from those and
                        other information either in our possession or likely to
                        come into our possession).
                      </p>
                    </div>

                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Usage Data
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        Usage Data is data collected automatically either
                        generated by the use of the Service or from the Service
                        infrastructure itself (for example, the duration of a
                        page visit).
                      </p>
                    </div>

                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Cookies
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        Cookies are small files stored on your device (computer
                        or mobile device).
                      </p>
                    </div>

                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Data Controller
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        Data Controller means the natural or legal person who
                        (either alone or jointly or in common with other
                        persons) determines the purposes for which and the
                        manner in which any personal information are, or are to
                        be, processed.
                      </p>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        For the purpose of this Privacy Policy, we are a Data
                        Controller of your Personal Data.
                      </p>
                    </div>

                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Data Processors (or Service Providers)
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        Data Processor (or Service Provider) means any natural
                        or legal person who processes the data on behalf of the
                        Data Controller.
                      </p>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        We may use the services of various Service Providers in
                        order to process your data more effectively.
                      </p>
                    </div>

                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Data Subject (or User)
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        Data Subject is any living individual who is using our
                        Service and is the subject of Personal Data.
                      </p>
                    </div>
                  </div>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Information Collection and Use
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    We collect several different types of information for
                    various purposes to provide and improve our Service to you.
                  </p>

                  <div className="space-y-4 mt-6">
                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Types of Data Collected
                      </h3>

                      <h4 className="font-sans text-sm text-foreground font-medium mb-2 mt-4">
                        Personal Data
                      </h4>
                      <p className="text-muted-foreground leading-relaxed">
                        While using our Service, we may ask you to provide us
                        with certain personally identifiable information that
                        can be used to contact or identify you ("Personal
                        Data"). Personally identifiable information may include,
                        but is not limited to:
                      </p>
                      <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4 mt-2">
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Cookies and Usage Data</li>
                      </ul>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        We may use your Personal Data to contact you with
                        newsletters, marketing or promotional materials and
                        other information that may be of interest to you. You
                        may opt out of receiving any, or all, of these
                        communications from us by following the unsubscribe link
                        or the instructions provided in any email we send.
                      </p>

                      <h4 className="font-sans text-sm text-foreground font-medium mb-2 mt-4">
                        Usage Data
                      </h4>
                      <p className="text-muted-foreground leading-relaxed">
                        When you access the Service with a mobile device, we may
                        collect certain information automatically, including,
                        but not limited to, the type of mobile device you use,
                        your mobile device unique ID, the IP address of your
                        mobile device, your mobile operating system, the type of
                        mobile Internet browser you use, unique device
                        identifiers and other diagnostic data ("Usage Data").
                      </p>

                      <h4 className="font-sans text-sm text-foreground font-medium mb-2 mt-4">
                        Tracking & Cookies Data
                      </h4>
                      <p className="text-muted-foreground leading-relaxed">
                        We use cookies and similar tracking technologies to
                        track the activity on our Service and we hold certain
                        information.
                      </p>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        Cookies are files with a small amount of data which may
                        include an anonymous unique identifier. Cookies are sent
                        to your browser from a website and stored on your
                        device. Other tracking technologies are also used such
                        as beacons, tags and scripts to collect and track
                        information and to improve and analyse our Service.
                      </p>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        You can instruct your browser to refuse all cookies or
                        to indicate when a cookie is being sent. However, if you
                        do not accept cookies, you may not be able to use some
                        portions of our Service.
                      </p>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        Examples of Cookies we use:
                      </p>
                      <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4 mt-2">
                        <li>
                          <strong>Session Cookies.</strong> We use Session
                          Cookies to operate our Service.
                        </li>
                        <li>
                          <strong>Preference Cookies.</strong> We use Preference
                          Cookies to remember your preferences and various
                          settings.
                        </li>
                        <li>
                          <strong>Security Cookies.</strong> We use Security
                          Cookies for security purposes.
                        </li>
                      </ul>
                    </div>
                  </div>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Use of Data
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    Midday Labs AB uses the collected data for various purposes:
                  </p>
                  <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                    <li>To provide and maintain our Service</li>
                    <li>To notify you about changes to our Service</li>
                    <li>
                      To allow you to participate in interactive features of our
                      Service when you choose to do so
                    </li>
                    <li>To provide customer support</li>
                    <li>
                      To gather analysis or valuable information so that we can
                      improve our Service
                    </li>
                    <li>To monitor the usage of our Service</li>
                    <li>To detect, prevent and address technical issues</li>
                    <li>
                      To provide you with news, special offers and general
                      information about other goods, services and events which
                      we offer that are similar to those that you have already
                      purchased or enquired about unless you have opted not to
                      receive such information
                    </li>
                  </ul>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Use of Google User Data
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    Midday's use of information received from Google APIs will
                    adhere to the Google API Services User Data Policy,
                    including the Limited Use requirements.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    We do not use any data obtained from Google Workspace APIs —
                    including Gmail data — to develop, improve, or train
                    generalized artificial intelligence (AI) or machine learning
                    (ML) models.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    User data accessed via Gmail scopes is used strictly for the
                    purpose of reading and extracting relevant information from
                    emails (such as invoices and receipts) to help users
                    automate and manage their business finances. This data is
                    never shared, sold, or used for advertising purposes.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Legal Basis for Processing Personal Data under the General
                    Data Protection Regulation (GDPR)
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    If you are from the European Economic Area (EEA), Midday
                    Labs AB legal basis for collecting and using the personal
                    information described in this Privacy Policy depends on the
                    Personal Data we collect and the specific context in which
                    we collect it.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    Midday Labs AB may process your Personal Data because:
                  </p>
                  <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                    <li>We need to perform a contract with you</li>
                    <li>You have given us permission to do so</li>
                    <li>
                      The processing is in our legitimate interests and it is
                      not overridden by your rights
                    </li>
                    <li>For payment processing purposes</li>
                    <li>To comply with the law</li>
                  </ul>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Retention of Data
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    Midday Labs AB will retain your Personal Data only for as
                    long as is necessary for the purposes set out in this
                    Privacy Policy. We will retain and use your Personal Data to
                    the extent necessary to comply with our legal obligations
                    (for example, if we are required to retain your data to
                    comply with applicable laws), resolve disputes and enforce
                    our legal agreements and policies.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    Midday Labs AB will also retain Usage Data for internal
                    analysis purposes. Usage Data is generally retained for a
                    shorter period of time, except when this data is used to
                    strengthen the security or to improve the functionality of
                    our Service, or we are legally obligated to retain this data
                    for longer periods.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Transfer of Data
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    Your information, including Personal Data, may be
                    transferred to - and maintained on - computers located
                    outside of your state, province, country or other
                    governmental jurisdiction where the data protection laws may
                    differ from those of your jurisdiction.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    If you are located outside Sweden and choose to provide
                    information to us, please note that we transfer the data,
                    including Personal Data, to Sweden and process it there.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    Your consent to this Privacy Policy followed by your
                    submission of such information represents your agreement to
                    that transfer.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    Midday Labs AB will take all the steps reasonably necessary
                    to ensure that your data is treated securely and in
                    accordance with this Privacy Policy and no transfer of your
                    Personal Data will take place to an organisation or a
                    country unless there are adequate controls in place
                    including the security of your data and other personal
                    information.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Disclosure of Data
                  </h2>

                  <div className="space-y-4">
                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Business Transaction
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        If Midday Labs AB is involved in a merger, acquisition
                        or asset sale, your Personal Data may be transferred. We
                        will provide notice before your Personal Data is
                        transferred and becomes subject to a different Privacy
                        Policy.
                      </p>
                    </div>

                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Disclosure for Law Enforcement
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        Under certain circumstances, Midday Labs AB may be
                        required to disclose your Personal Data if required to
                        do so by law or in response to valid requests by public
                        authorities (e.g. a court or a government agency).
                      </p>
                    </div>

                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Legal Requirements
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        Midday Labs AB may disclose your Personal Data in the
                        good faith belief that such action is necessary to:
                      </p>
                      <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                        <li>To comply with a legal obligation</li>
                        <li>
                          To protect and defend the rights or property of Midday
                          Labs AB
                        </li>
                        <li>
                          To prevent or investigate possible wrongdoing in
                          connection with the Service
                        </li>
                        <li>
                          To protect the personal safety of users of the Service
                          or the public
                        </li>
                        <li>To protect against legal liability</li>
                      </ul>
                    </div>
                  </div>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Security of Data
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    The security of your data is important to us but remember
                    that no method of transmission over the Internet or method
                    of electronic storage is 100% secure. While we strive to use
                    commercially acceptable means to protect your Personal Data,
                    we cannot guarantee its absolute security.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Our Policy on "Do Not Track" Signals under the California
                    Online Protection Act (CalOPPA)
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    We do not support Do Not Track ("DNT"). Do Not Track is a
                    preference you can set in your web browser to inform
                    websites that you do not want to be tracked.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    You can enable or disable Do Not Track by visiting the
                    Preferences or Settings page of your web browser.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Your Data Protection Rights under the General Data
                    Protection Regulation (GDPR)
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    If you are a resident of the European Economic Area (EEA),
                    you have certain data protection rights. Midday Labs AB aims
                    to take reasonable steps to allow you to correct, amend,
                    delete or limit the use of your Personal Data.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    If you wish to be informed about what Personal Data we hold
                    about you and if you want it to be removed from our systems,
                    please contact us.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    In certain circumstances, you have the following data
                    protection rights:
                  </p>
                  <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4">
                    <li>
                      <strong>
                        The right to access, update or delete the information we
                        have on you.
                      </strong>{" "}
                      Whenever made possible, you can access, update or request
                      deletion of your Personal Data directly within your
                      account settings section. If you are unable to perform
                      these actions yourself, please contact us to assist you.
                    </li>
                    <li>
                      <strong>The right of rectification.</strong> You have the
                      right to have your information rectified if that
                      information is inaccurate or incomplete.
                    </li>
                    <li>
                      <strong>The right to object.</strong> You have the right
                      to object to our processing of your Personal Data.
                    </li>
                    <li>
                      <strong>The right of restriction.</strong> You have the
                      right to request that we restrict the processing of your
                      personal information.
                    </li>
                    <li>
                      <strong>The right to data portability.</strong> You have
                      the right to be provided with a copy of the information we
                      have on you in a structured, machine-readable and commonly
                      used format.
                    </li>
                    <li>
                      <strong>The right to withdraw consent.</strong> You also
                      have the right to withdraw your consent at any time where
                      Midday Labs AB relied on your consent to process your
                      personal information.
                    </li>
                  </ul>
                  <p className="text-muted-foreground leading-relaxed mt-2">
                    Please note that we may ask you to verify your identity
                    before responding to such requests.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    You have the right to complain to a Data Protection
                    Authority about our collection and use of your Personal
                    Data. For more information, please contact your local data
                    protection authority in the European Economic Area (EEA).
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Service Providers
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    We may employ third party companies and individuals to
                    facilitate our Service ("Service Providers"), provide the
                    Service on our behalf, perform Service-related services or
                    assist us in analysing how our Service is used.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    These third parties have access to your Personal Data only
                    to perform these tasks on our behalf and are obligated not
                    to disclose or use it for any other purpose.
                  </p>

                  <div className="space-y-4 mt-6">
                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Analytics
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        We may use third-party Service Providers to monitor and
                        analyse the use of our Service.
                      </p>

                      <h4 className="font-sans text-sm text-foreground font-medium mb-2 mt-4">
                        Firebase
                      </h4>
                      <p className="text-muted-foreground leading-relaxed">
                        Firebase is analytics service provided by Google Inc.
                      </p>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        You may opt-out of certain Firebase features through
                        your mobile device settings, such as your device
                        advertising settings or by following the instructions
                        provided by Google in their Privacy Policy:{" "}
                        <a
                          href="https://policies.google.com/privacy?hl=en"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-foreground hover:text-muted-foreground transition-colors underline"
                        >
                          https://policies.google.com/privacy?hl=en
                        </a>
                      </p>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        We also encourage you to review the Google's policy for
                        safeguarding your data:{" "}
                        <a
                          href="https://support.google.com/analytics/answer/6004245"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-foreground hover:text-muted-foreground transition-colors underline"
                        >
                          https://support.google.com/analytics/answer/6004245
                        </a>
                        .
                      </p>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        For more information on what type of information
                        Firebase collects, please visit the Google Privacy &
                        Terms web page:{" "}
                        <a
                          href="https://policies.google.com/privacy?hl=en"
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-foreground hover:text-muted-foreground transition-colors underline"
                        >
                          https://policies.google.com/privacy?hl=en
                        </a>
                      </p>
                    </div>

                    <div>
                      <h3 className="font-sans text-sm text-foreground font-medium mb-2">
                        Payments
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        We may provide paid products and/or services within the
                        Service. In that case, we use third-party services for
                        payment processing (e.g. payment processors).
                      </p>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        We will not store or collect your payment card details.
                        That information is provided directly to our third-party
                        payment processors whose use of your personal
                        information is governed by their Privacy Policy. These
                        payment processors adhere to the standards set by
                        PCI-DSS as managed by the PCI Security Standards
                        Council, which is a joint effort of brands like Visa,
                        MasterCard, American Express and Discover. PCI-DSS
                        requirements help ensure the secure handling of payment
                        information.
                      </p>
                      <p className="text-muted-foreground leading-relaxed mt-2">
                        The payment processors we work with are:
                      </p>
                      <ul className="list-disc list-inside space-y-2 text-muted-foreground ml-4 mt-2">
                        <li>
                          <strong>Apple Store In-App Payments</strong>
                          <br />
                          Their Privacy Policy can be viewed at{" "}
                          <a
                            href="https://www.apple.com/legal/privacy/en-ww/"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-foreground hover:text-muted-foreground transition-colors underline"
                          >
                            https://www.apple.com/legal/privacy/en-ww/
                          </a>
                        </li>
                        <li>
                          <strong>Google Play In-App Payments</strong>
                          <br />
                          Their Privacy Policy can be viewed at{" "}
                          <a
                            href="https://www.google.com/policies/privacy/"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-foreground hover:text-muted-foreground transition-colors underline"
                          >
                            https://www.google.com/policies/privacy/
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Links to Other Sites
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    Our Service may contain links to other sites that are not
                    operated by us. If you click a third party link, you will be
                    directed to that third party's site. We strongly advise you
                    to review the Privacy Policy of every site you visit.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    We have no control over and assume no responsibility for the
                    content, privacy policies or practices of any third party
                    sites or services.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Children's Privacy
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    Our Service does not address anyone under the age of 18
                    ("Children").
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    We do not knowingly collect personally identifiable
                    information from anyone under the age of 18. If you are a
                    parent or guardian and you are aware that your Child has
                    provided us with Personal Data, please contact us. If we
                    become aware that we have collected Personal Data from
                    children without verification of parental consent, we take
                    steps to remove that information from our servers.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Changes to This Privacy Policy
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    We may update our Privacy Policy from time to time. We will
                    notify you of any changes by posting the new Privacy Policy
                    on this page.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    We will let you know via email and/or a prominent notice on
                    our Service, prior to the change becoming effective and
                    update the "effective date" at the top of this Privacy
                    Policy.
                  </p>
                  <p className="text-muted-foreground leading-relaxed">
                    You are advised to review this Privacy Policy periodically
                    for any changes. Changes to this Privacy Policy are
                    effective when they are posted on this page.
                  </p>
                </section>

                <section className="space-y-4">
                  <h2 className="font-sans text-base text-foreground mt-8 mb-4">
                    Contact Us
                  </h2>
                  <p className="text-muted-foreground leading-relaxed">
                    If you have any questions about this Privacy Policy, please
                    contact us:
                  </p>
                  <p className="text-foreground leading-relaxed">
                    By email:{" "}
                    <a
                      href="mailto:support@midday.ai"
                      className="text-foreground hover:text-muted-foreground transition-colors"
                    >
                      support@midday.ai
                    </a>
                  </p>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
