/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vPGutDVP0E7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { CameraIcon, CircleIcon, CurrencyIcon, ImageIcon, MapIcon, Music2Icon, PencilIcon, StickerIcon, VideoIcon, VolumeIcon, XIcon } from "lucide-react"
import React from "react"
import ChatAccessibilityButton from "./chat-accessibility-button"

export function AccessibilityWidget() {
  const [isOpen, setIsOpen] = React.useState(false)
  return (
    <div className="relative">
      <button
        className="fixed bottom-0 m-4 hidden sm:block left-20 w-12 h-12 rounded-full bg-primary text-primary-foreground items-center justify-center shadow-lg"
        onClick={() => setIsOpen(!isOpen)}
      >
        {isOpen ? <XIcon className="w-6 h-6" /> : <CircleIcon className="w-6 h-6" />}
        <span className="sr-only">{isOpen ? "Close Menu" : "Open Menu"}</span>
      </button>
      {isOpen && (
        <div className="fixed inset-0 z-50 backdrop-blur-sm">
          <Card className="fixed bottom-20 left-20 p-6 shadow-lg md:min-w-[200px]">
            <div className="flex justify-between items-center mb-4">
              <Button variant="ghost" size="icon" onClick={() => setIsOpen(false)}>
                <XIcon className="h-6 w-6" />
                <span className="sr-only">Close</span>
              </Button>
            </div>
            <div className="flex flex-col md:max-h-96 scrollbar-hide overflow-y-auto my-[2.5%] md:min-h-64">
              <div className="flex flex-col gap-4 items-start">
                <Button variant="ghost" className="flex flex-1 items-center gap-2 border-0">
                  <ChatAccessibilityButton className="m-3" />
                  <span className="text-lg">Ask Solomon</span>
                </Button>
              </div>
            </div>
          </Card>
        </div>
      )}
    </div>
  )
}
